### ISSUE TITLE
[BUG] Improper access control leads access to all team

### ISSUE THREAD

**Issue by W0rty** [CTF-Cafe/CTF_Cafe_platform#100]
There is an improper access control on the API that leads any user to recover the secret code of any team.

The attacker just have to send a POST request to /api/user/getTeamCode with the team name and can join the team.

To fix, you have to verify that the user that is requested the code is a member of the requested team.

**Comment by Gomez0015** [comment]
Does this not prevent it : https://github.com/CTF-Cafe/CTF_Cafe_platform/blob/master/backEnd/controllers/teamController.js#L86
