### ISSUE TITLE
Not properly working on chrome

### ISSUE THREAD

**Issue by mpgn** [CTF-Cafe/CTF_Cafe_platform#97]
Hello, I decided to try this new platform and take the easy way with `docker compose up`.

Site is loading, no problem except for the typo #96 , Now I want to connect but credential `admin:admin` is not working (it's from the readme) and creating a user account show at the same time two opposite messages. When trying to connect with this new account, it doesn't work ofc.

What i'm missing ?

![image](https://user-images.githubusercontent.com/5891788/232221515-4ad2e633-6eb8-4284-b254-2a106b0b5a51.png)

**Comment by mpgn** [comment]
I just realise the site is only working on Firefox and not chrome (i'm on linux) on my side.
I can now login with Firefox with a user that I register.

**Comment by mpgn** [comment]
Finaly

![image](https://user-images.githubusercontent.com/5891788/232254008-97ed2cf8-a4eb-4550-aba5-6d3a9adaebbe.png)

A bit sad it doesn't work on chrome, when trying to login you will see this, but you are never really connected 

![image](https://user-images.githubusercontent.com/5891788/232254040-385c90f2-5ab8-4142-b7fc-b5ee8a7087fc.png)

**Comment by mpgn** [comment]
My version of chrome 

![image](https://user-images.githubusercontent.com/5891788/232254070-c6dfc7cf-887b-449a-8b60-1de79365dab8.png)

**Comment by Gomez0015** [comment]
Hey, are you running this on a VPS? It should properly work on chrome, and for the admin password yeah, it is not mentioned yet. But I am working on a documentation which I will publish soon. We could hop a discord call quickly if you want me to help you debug the chrome bug, and lastly thanks for the merge !

**Comment by mpgn** [comment]
For sure @Gomez0015 I have also other questions can you add me on discord: flibustier#2816
